### ISSUE TITLE
improve error message on password recovery fail

### ISSUE THREAD

**Issue by dennissherman** [niquerio/mk-peerage#24]
The error message for bad email in password recovery is opaque and scary for non-technical users.

Replication:
1) navigate to password recovery  (Private chambers > Forgot your password)
2) enter an unknown email address
3) select "Send reset instructions"

Both too much and not enough information is shown in the error message. It is too detailed for non-technical users ("error prohibited" is scary) and not detailed enough, without any suggestion for what to do about it.

**Comment by niquerio** [comment]
Changed in pull-request: #30
Build with change can be found here: https://mk-peerage-staging-pr-30.herokuapp.com/users/password
Error message should look like this now: 
![image](https://user-images.githubusercontent.com/4235919/37877276-874be548-3026-11e8-998f-4e89f597b119.png)

**Comment by niquerio** [comment]
Merged in.
