### ISSUE TITLE
Image as tap target on mobile

### ISSUE THREAD

**Issue by dennissherman** [niquerio/mk-peerage#28]
On mobile device, viewing candidates would be easier if their image was a tap target, as well as their name.

Replication: navigate to private chambers
Select watch list
Tap photo, nothing happens

**Comment by niquerio** [comment]
Fixed in: #31 
Can be viewed here: https://mk-peerage-staging-pr-31.herokuapp.com/

**Comment by niquerio** [comment]
Merged in.
